### ISSUE TITLE
Fix web scraping after changes on Tagesschau Website

### ISSUE THREAD

**Issue by GollyTicker** [GollyTicker/tagesschau-corona-counter#33]
The tagesschau website has changes as the web-scraping does not work anymore. The following exception trace happens during web scraping:

```
Getting topics for date 2022-06-08 00:00:00
GET https://www.tagesschau.de/archiv/sendungsarchiv100~_date-20220608.html
ERROR: anchor link to subpage not found!
Traceback (most recent call last):
  File "/app/src/1-download-data.py", line 132, in <module>
    main()
  File "/app/src/1-download-data.py", line 20, in main
    subpage_url = extract_url_to_subpage(date_html)
  File "/app/src/1-download-data.py", line 82, in extract_url_to_subpage
    error_on_empty(links, "anchor link to subpage")
  File "/app/src/1-download-data.py", line 100, in error_on_empty
    raise ValueError
ValueError
```

**Comment by GollyTicker** [comment]
Actually, there was no tagesschau on 8th June 2022 - which is why this extraction did not work.

https://www.tagesschau.de/archiv/sendungsarchiv100~_date-20220608.html

**Comment by GollyTicker** [comment]
Adding an exception for this date resolveds the problem:
https://github.com/GollyTicker/tagesschau-corona-counter/commit/f430bfedb76ebcd93a299ec9d23a92eb395505ca
